src/GotChosen/SiteBundle/Entity/Scholarship.php
<?php

namespace GotChosen\SiteBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use GotChosen\Util\Enums;

/**
 * Scholarship
 *
 * @ORM\Table(name="Scholarships")
 * @ORM\Entity(repositoryClass="GotChosen\SiteBundle\Repository\ScholarshipRepository")
 */
class Scholarship
{
    // scholarship types -- 40k, monthly, video. for special behaviors.
    // 40k allows sponsorship (in ScholarshipEntry), video has voting.

    const TYPE_40K = 1;
    const TYPE_MONTHLY = 2;
    const TYPE_VIDEO = 3;
    const TYPE_EVOGAMES = 4;

    static public $scholarshipTypes = [
        self::TYPE_40K => '40K Scholarship',
        self::TYPE_MONTHLY => 'Monthly Scholarship',
        self::TYPE_VIDEO => 'Video Scholarship',
        self::TYPE_EVOGAMES => 'Evolution Games',
    ];

    /**
     * @var integer
     *
     * @ORM\Column(name="idScholarships", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="ScholarshipName", type="string", length=200)
     */
    private $scholarshipName;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="StartDate", type="datetime")
     */
    private $startDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="EndDate", type="datetime")
     */
    private $endDate;

    /**
     * @var int
     *
     * @ORM\Column(name="ScholarshipType", type="smallint")
     */
    private $scholarshipType;
    
    /**
     * @var int 
     * 
     * @ORM\Column(name="DrawingComplete", type="boolean")
     */
    private $drawingComplete;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="ScholarshipEntry", mappedBy="scholarship")
     */
    private $entries;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="VideoCategory", mappedBy="scholarship")
     */
    private $categories;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Video", mappedBy="scholarship")
     */
    private $videos;

    /**
     * @param $type
     * @return Scholarship
     */
    static public function createFake($type)
    {
        Enums::assert($type, self::$scholarshipTypes);

        $ss = new Scholarship();
        $ss->id = 0;
        $ss->scholarshipType = $type;
        $ss->startDate = date_create('first day of this month')->setTime(0, 0, 0);
        $ss->endDate = date_create('last day of this month')->setTime(23, 59, 59);

        return $ss;
    }
  
    
    public function __construct()
    {
        $this->entries = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->videos = new ArrayCollection();
    }

    // meh
    public function getRulesRoute()
    {
        $type = $this->getScholarshipType();
        if ( $type === self::TYPE_40K ) {
            return ['scholarship', ['tab' => 'rules']];
        } else if ( $type === self::TYPE_MONTHLY ) {
            return ['monthly_scholarship', ['tab' => 'rules']];
        } else {
            return ['video_scholarship', ['tab' => 'about']];
        }
    }

    public function is40K()
    {
        return $this->getScholarshipType() == self::TYPE_40K;
    }
    
    public function isMonthly()
    {
        return $this->getScholarshipType() == self::TYPE_MONTHLY;
    }
    
    public function isEvoGames()
    {
        return $this->getScholarshipType() == self::TYPE_EVOGAMES;
    }
    
    public function isVideo() {
        return $this->getScholarshipType() == self::TYPE_VIDEO;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set scholarshipName
     *
     * @param string $scholarshipName
     * @return Scholarship
     */
    public function setScholarshipName($scholarshipName)
    {
        $this->scholarshipName = $scholarshipName;
    
        return $this;
    }

    /**
     * Get scholarshipName
     *
     * @return string 
     */
    public function getScholarshipName()
    {
        return $this->scholarshipName;
    }

    /**
     * Set startDate
     *
     * @param \DateTime $startDate
     * @return Scholarship
     */
    public function setStartDate($startDate)
    {
        $this->startDate = $startDate;
    
        return $this;
    }

    /**
     * Get startDate
     *
     * @return \DateTime 
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * Set endDate
     *
     * @param \DateTime $endDate
     * @return Scholarship
     */
    public function setEndDate($endDate)
    {
        $this->endDate = $endDate;
    
        return $this;
    }

    /**
     * Get endDate
     *
     * @return \DateTime 
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * Set scholarshipType
     *
     * @param integer $scholarshipType
     * @throws \InvalidArgumentException
     * @return Scholarship
     */
    public function setScholarshipType($scholarshipType)
    {
        Enums::assert($scholarshipType, self::$scholarshipTypes);
        $this->scholarshipType = $scholarshipType;
    
        return $this;
    }

    /**
     * Get scholarshipType
     *
     * @return integer 
     */
    public function getScholarshipType()
    {
        return $this->scholarshipType;
    }
    
    /**
     * Set drawingComplete
     * 
     * @param boolean $complete
     * @return Scholarship
     */
    public function setDrawingComplete($complete)
    {
        $this->drawingComplete = $complete;
        
        return $this;
    }
    
    public function isDrawingComplete()
    {
        return $this->drawingComplete;
    }
    
    /**
     * Add entries
     *
     * @param ScholarshipEntry $entries
     * @return Scholarship
     */
    public function addEntry(ScholarshipEntry $entries)
    {
        $this->entries[] = $entries;
    
        return $this;
    }

    /**
     * Remove entries
     *
     * @param ScholarshipEntry $entries
     */
    public function removeEntry(ScholarshipEntry $entries)
    {
        $this->entries->removeElement($entries);
    }

    /**
     * Get entries
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getEntries()
    {
        return $this->entries;
    }
}

src/GotChosen/SiteBundle/Entity/User.php
<?php

namespace GotChosen\SiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use FOS\UserBundle\Model\User as BaseUser;
use GotChosen\Util\Strings;
use Symfony\Component\Routing\Generator\UrlGenerator;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Routing\RouterInterface;

/**
 * User
 *
 * @ORM\Table(indexes={
 *      @ORM\Index(name="Username", columns={"username"}),
 *      @ORM\Index(name="Username_Password", columns={"username", "password", "salt"}),
 *      @ORM\Index(name="Status", columns={"status"}),
 *      @ORM\Index(name="CreatedDate", columns={"createdDate"}),
 *      @ORM\Index(name="LastModified", columns={"lastModified"}),
 *      @ORM\Index(name="ConfirmationToken", columns={"confirmation_token"})}
 * )
 * @ORM\Entity(repositoryClass="GotChosen\SiteBundle\Repository\UserRepository")
 */
class User extends BaseUser
{
    /**
     * User status constants.
     *
     * ACTIVE = Verified account.
     * AWAITING_VERIFICATION = Confirmation e-mail pending.
     * NOT_CONVERTED = Old platform user, still GUID name.
     * DISABLED_USER = User "deleted" themselves through profile.
     * DISABLED_ADMIN = Admin manually disabled user.
     * BAD_EMAIL = User auto-disabled for having a bad e-mail address.
     */
    const STATUS_ACTIVE = 'active';
    const STATUS_AWAITING_VERIFICATION = 'unconfirmed';
    const STATUS_NOT_CONVERTED = 'not_converted';
    const STATUS_DISABLED_USER = 'user_disabled';
    const STATUS_DISABLED_ADMIN = 'admin_disabled';
    const STATUS_BAD_EMAIL = 'bad_email';

    public static $status_types = [
        self::STATUS_ACTIVE => 'Active User',
        self::STATUS_AWAITING_VERIFICATION => 'Unconfirmed User',
        self::STATUS_NOT_CONVERTED => 'Unconverted Old Platform User',
        self::STATUS_DISABLED_USER => 'Disabled User (Self)',
        self::STATUS_DISABLED_ADMIN => 'Disabled User (Admin)',
        self::STATUS_BAD_EMAIL => 'Disabled User (Bad E-mail)'
    ];

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdDate", type="datetime")
     */
    protected $createdDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="lastModified", type="datetime")
     */
    protected $lastModified;

    /**
     * @var string
     *
     * @ORM\Column(name="status", type="string", length=50)
     */
    protected $status;

    /**
     * @var integer
     *
     * @ORM\Column(name="tokens", type="integer")
     */
    protected $tokens;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="UserProfile", mappedBy="user")
     */
    protected $profile;

    /**
     * Named "customRoles" since "roles" already exists in the base model.
     *
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Role", inversedBy="users")
     */
    protected $customRoles;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="UsergMeshNetwork", mappedBy="ownerUser")
     */
    protected $ownedNetworks;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="UsersInNetworks", mappedBy="user")
     */
    protected $networks;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="ScholarshipEntry", mappedBy="user")
     */
    protected $scholarshipEntries;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="NotificationSub", mappedBy="user")
     */
    protected $notificationSubs;

    /**
     * @var integer
     *
     * @ORM\Column(name="totalWins", type="integer")
     */
    protected $totalWins;

    /**
     * @var integer
     *
     * @ORM\Column(name="totalLosses", type="integer")
     */
    protected $totalLosses;

    /**
     * @var array
     */
    protected $cachedPropertyValues = null;

    /**
     * Constructor
     */

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Video", mappedBy="user")
     */
    private $videos;

    public function __construct()
    {
        parent::__construct();

        $this->profile = new ArrayCollection();
        $this->customRoles = new ArrayCollection();
        $this->ownedNetworks = new ArrayCollection();
        $this->networks = new ArrayCollection();
        $this->scholarshipEntries = new ArrayCollection();
        $this->notificationSubs = new ArrayCollection();
        $this->videos = new ArrayCollection();

        $this->createdDate = new \DateTime('now');
        $this->lastModified = new \DateTime('now');

        $this->tokens = 0;
        $this->totalWins = 0;
        $this->totalLosses = 0;
    }

    /**
     * Overrides BaseUser::getRoles so we can merge additional custom roles from the DB.
     *
     * @return array
     */
    public function getRoles()
    {
        $roles = parent::getRoles();
        /** @var $customRole Role */
        foreach ( $this->getCustomRoles() as $customRole ) {
            $roles[] = $customRole->getRoleName();
        }

        return array_unique($roles);
    }

    protected function cacheProperties()
    {
        if ( is_array($this->cachedPropertyValues) ) {
            return;
        }

        $this->cachedPropertyValues = [];

        /** @var $profileProp UserProfile */
        foreach ( $this->profile as $profileProp ) {
            $key = $profileProp->getProperty()->getName();
            $value = $profileProp->getPropertyValue();
            $this->cachedPropertyValues[$key] = $value;
        }
    }

    public function getCachedProperties()
    {
        $this->cacheProperties();
        return $this->cachedPropertyValues;
    }

    /**
     * @param array $properties
     * @internal
     * @see UserRepository::precacheProperties
     */
    public function setCachedProperties(array $properties)
    {
        $this->cachedPropertyValues = $properties;
    }

    public function getPropertyValue($key, $default = null)
    {
        $this->cacheProperties();

        return isset($this->cachedPropertyValues[$key]) ? $this->cachedPropertyValues[$key] : $default;
    }

    public function getFullName()
    {
        return $this->getPropertyValue("FirstName", '') . ' ' . $this->getPropertyValue("LastName", '');
    }

    public function getScholarshipEntry(Scholarship $sship)
    {
        /** @var ScholarshipEntry[] $entries */
        $entries = $this->getScholarshipEntries();
        foreach ( $entries as $entry ) {
            if ( $entry->getScholarship()->getId() == $sship->getId() ) {
                return $entry;
            }
        }
        return null;
    }

    public function hasApplied(Scholarship $sship)
    {
        return $this->getScholarshipEntry($sship) !== null;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set createdDate
     *
     * @param \DateTime $createdDate
     * @return User
     */
    public function setCreatedDate($createdDate)
    {
        $this->createdDate = $createdDate;

        return $this;
    }

    /**
     * Get createdDate
     *
     * @return \DateTime
     */
    public function getCreatedDate()
    {
        return $this->createdDate;
    }

    /**
     * Set lastModified
     *
     * @param \DateTime $lastModified
     * @return User
     */
    public function setLastModified($lastModified)
    {
        $this->lastModified = $lastModified;

        return $this;
    }

    /**
     * Get lastModified
     *
     * @return \DateTime
     */
    public function getLastModified()
    {
        return $this->lastModified;
    }

    /**
     * Set status
     *
     * @param string $status
     * @return User
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status/
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @return int
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     * @param $tokens
     * @return $this
     */
    public function setTokens($tokens)
    {
        $this->tokens = $tokens;
        return $this;
    }

    /**
     * Add profile
     *
     * @param UserProfile $profile
     * @return User
     */
    public function addProfile(UserProfile $profile)
    {
        $this->profile[] = $profile;

        return $this;
    }

    /**
     * Remove profile
     *
     * @param UserProfile $profile
     */
    public function removeProfile(UserProfile $profile)
    {
        $this->profile->removeElement($profile);
    }

    /**
     * Get profile
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * Add ownedNetworks
     *
     * @param UsergMeshNetwork $ownedNetworks
     * @return User
     */
    public function addOwnedNetwork(UsergMeshNetwork $ownedNetworks)
    {
        $this->ownedNetworks[] = $ownedNetworks;

        return $this;
    }

    /**
     * Remove ownedNetworks
     *
     * @param UsergMeshNetwork $ownedNetworks
     */
    public function removeOwnedNetwork(UsergMeshNetwork $ownedNetworks)
    {
        $this->ownedNetworks->removeElement($ownedNetworks);
    }

    /**
     * Get ownedNetworks
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getOwnedNetworks()
    {
        return $this->ownedNetworks;
    }

    /**
     * Add networks
     *
     * @param UsersInNetworks $networks
     * @return User
     */
    public function addNetwork(UsersInNetworks $networks)
    {
        $this->networks[] = $networks;

        return $this;
    }

    /**

src/GotChosen/SiteBundle/Resources/views/Scholarship/apply.html.twig
{% extends 'GotChosenSiteBundle::layout_front_content.html.twig' %}

{% form_theme form _self %}
{% block label_asterisk %}{% if required %}<span class="req">*</span>{% endif %}{% endblock %}

{% block title %} {{ scholarship.scholarshipName }} | {{ parent() }}{% endblock %}

{% block body %}

<div class="content">
    <div class="main padded wide profile">
        <h1 class="title">
            {{ scholarship.scholarshipName|e|gc_autosuper }}
            <span class="title-bar" style="width:700px;"></span>
        </h1>

        <p><span class="req-note">* Denotes required fields</span></p>

        {{ form_start(form, {'attr': {'class': 'form-horizontal scholarship-app'}}) }}

        <fieldset>
            <legend>Contact Information</legend>

            {% for propkey in contactPropKeys %}
                <div id="form_{{ propkey }}_control_group" class="control-group">
                    {{ form_label(form[propkey]) }}
                    <div class="controls">
                        {{ form_widget(form[propkey]) }}

                        {% if form["privacy_" ~ propkey] is defined %}
                            {{ form_widget(form["privacy_" ~ propkey], {'attr': {'class': 'privacy-setting'}}) }}
                        {% endif %}

                        {{ form_errors(form[propkey]) }}
                    </div>
                </div>
            {% endfor %}
        </fieldset>

        <fieldset>
            <legend>Education Information</legend>

            {% for propkey in educationPropKeys %}
                <div id="form_{{ propkey }}_control_group" class="control-group">
                    {{ form_label(form[propkey]) }}
                    <div class="controls">
                        {{ form_widget(form[propkey]) }}

                        {% if form["privacy_" ~ propkey] is defined %}
                            {{ form_widget(form["privacy_" ~ propkey], {'attr': {'class': 'privacy-setting'}}) }}
                        {% endif %}

                        {{ form_errors(form[propkey]) }}
                    </div>
                </div>
            {% endfor %}
        </fieldset>

        {{ form_rest(form) }}

        {% set rules = scholarship.rulesRoute %}
        <p class="rules-note">By clicking Submit Application, you agree to the
            <a href="#terms-{{ rules[0] }}" data-toggle="modal">rules and regulations</a> for this scholarship.
        </p>

        <div class="submit-row">
            <input class="btn btn-primary" type="submit" value="Submit Application" />
            &nbsp;&nbsp;&nbsp;<a href="{{ path('user_my_profile') }}">Cancel</a>
        </div>

        {{ form_end(form) }}
    </div>
</div>

    <div id="terms-scholarship" class="modal hide fade" tabindex="-1" role="dialog"
         aria-labelledby="scholarshipLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="scholarshipLabel">$20K Scholarship Rules &amp; Regulations</h3>
        </div>
        <div class="modal-body">
            {% include 'GotChosenSiteBundle::terms_40k.html.twig' %}
        </div>
    </div>

    <div id="terms-monthly_scholarship" class="modal hide fade" tabindex="-1" role="dialog"
         aria-labelledby="monthScholarshipLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="monthScholarshipLabel">Monthly Scholarship Rules &amp; Regulations</h3>
        </div>
        <div class="modal-body">
            {% include 'GotChosenSiteBundle::terms_monthly.html.twig' %}
        </div>
    </div>

    <div id="terms-video_scholarship" class="modal hide fade" tabindex="-1" role="dialog"
         aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="modalLabel">VideoScholarship Rules &amp; Regulations</h3>
        </div>
        <div class="modal-body">
            {% include 'GotChosenSiteBundle::terms_video.html.twig' %}
        </div>
    </div>

{% endblock %}
{% block javascripts %}
{{ parent() }}
<script type="text/javascript">
$(function(){
    $('textarea.maxlength').maxCharacters('.controls');
});
</script>
{% endblock %}

src/GotChosen/SiteBundle/Resources/views/Scholarship/sponsor.html.twig
{% extends 'GotChosenSiteBundle::layout_front_content.html.twig' %}

{% block title %} Sponsor {{ user.fullName }} | {{ parent() }}{% endblock %}

{% block body %}

    <div class="content">
        <div class="main padded wide profile">
            <h1 class="title">
                Sponsor {{ user.fullName }}
                <span class="title-bar" style="width:800px;"></span>
            </h1>

            {% if app.user %}

                {{ form_start(form) }}

                <p>Thank you for considering a sponsorship of
                    <a href="{{ path('user_profile', {'username': user.username}) }}">{{ user.fullName }}</a>.
                    To confirm your sponsorship, click the relevant button below. You may also read more
                    information about the scholarship, or apply for the scholarship yourself.
                </p>

                <p style="text-align: center">
                    <input type="submit" value="Confirm Sponsorship" class="btn btn-primary" />
                    &nbsp;
                    <a class="btn" target="_blank" href="{{ path('scholarship') }}">More Information</a>
                    {% if not app.user.hasApplied(scholarship) %}
                        &nbsp;
                        <a class="btn" target="_blank"
                           href="{{ path('scholarship_apply', {'id': scholarship.id}) }}">Apply for Scholarship</a>
                    {% endif %}
                </p>

                {{ form_end(form) }}

            {% else %}
                <p>
                    Welcome! In order to confirm your sponsorship of
                    <a href="{{ path('user_profile', {'username': user.username}) }}">{{ user.fullName }}</a>,
                    please log in. If you do not yet have an account, please sign up for one.
                </p>
                <p style="text-align: center">
                    <a class="btn" href="{{ loginUrl }}">Log in</a>
                    &nbsp;
                    <a class="btn" href="{{ registerUrl }}">Register</a>
                </p>
            {% endif %}
        </div>
    </div>

{% endblock %}

src/GotChosen/SiteBundle/Resources/views/Scholarship/sponsorThanks.html.twig
{% extends 'GotChosenSiteBundle::layout_front_content.html.twig' %}

{% block title %} Sponsor {{ user.fullName }} | {{ parent() }}{% endblock %}

{% block body %}

    <div class="content">
        <div class="main padded wide profile">
            <h1 class="title">
                Sponsor {{ user.fullName }}
                <span class="title-bar" style="width:800px;"></span>
            </h1>

            <p>Thank you for sponsoring {{ user.fullName }}!</p>

            <p style="text-align: center">
                <a class="btn" href="{{ path('user_profile', {'username': user.username}) }}">
                    {{ user.fullName }}'s Profile</a>
                &nbsp;
                <a class="btn" href="{{ path('user_my_profile') }}">My Profile</a>

                {% if scholarship and not app.user.hasApplied(scholarship) %}
                    &nbsp;
                    <a class="btn"
                       href="{{ path('scholarship_apply', {'id': scholarship.id}) }}">Apply for Scholarship</a>
                {% endif %}
            </p>
        </div>
    </div>

{% endblock %}